### ISSUE TITLE
Error: invalid_request  Missing required parameter: redirect_uri

### ISSUE THREAD

**Issue by rahul3883** [numsu/google-drive-sdk-api-php-insert-file-parent-example#1]
i got an error 

```
Error: invalid_request
Missing required parameter: redirect_uri
```

request details : 
access_type=offline
approval_prompt=auto
user_id=myemailid
scope=https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
response_type=code
state=

**Comment by rahul3883** [comment]
i figured it out, the issue is solved.

**Comment by numsu** [comment]
Great to hear! Are the instructions unclear on some part or do I need to add in something? Thanks.
